FROM python:3.11-slim

WORKDIR /app

# Copiar primero requirements.txt para aprovechar la caché de Docker
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto de archivos
COPY api/ /app/

# CMD para iniciar la aplicación Flask con gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
