name: Refresh Exchange Rate Redis

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  call-api-endpoints:
    runs-on: ubuntu-latest

    steps:
      - name: Call PEN endpoint
        run: curl -L --silent --show-error --fail https://exchangerate.brianuceda.xyz/api/v1/PEN/1 || true

      - name: Call USD endpoint
        run: curl -L --silent --show-error --fail https://exchangerate.brianuceda.xyz/api/v1/USD/1 || true

      - name: Call CAD endpoint
        run: curl -L --silent --show-error --fail https://exchangerate.brianuceda.xyz/api/v1/CAD/1 || true

      - name: Call EUR endpoint
        run: curl -L --silent --show-error --fail https://exchangerate.brianuceda.xyz/api/v1/EUR/1 || true
